#!/usr/bin/env bash

PROFILE_NAME="muse-glimmer-30b-q5km-vulkan-q8-16k"

LLAMA_BINARY="$LLM_ROOT/llama.cpp/build-vulkan/bin/llama-server"
LLAMA_MODEL="$LLAMA_SERVER_ROOT/models/Muse-Glimmer-30B-UD-Q5_K_M.gguf"
LLAMA_ALIAS="local"

LLAMA_BACKEND="vulkan"
LLAMA_DEVICE="Vulkan0"
LLAMA_GPU_LAYERS=99
LLAMA_CONTEXT=16384
LLAMA_THREADS="auto"
LLAMA_BATCH_THREADS="auto"
LLAMA_PARALLEL=1
LLAMA_UBATCH=192

LLAMA_CACHE_TYPE_K="q8_0"
LLAMA_CACHE_TYPE_V="q8_0"
LLAMA_CACHE_RAM=""
LLAMA_FLASH_ATTN="on"
LLAMA_CONTEXT_SHIFT=1

LLAMA_SPEC_MODE="none"
LLAMA_DRAFTER=""

LLAMA_TEMPERATURE=0.7
LLAMA_TOP_P=1.0
LLAMA_TOP_K=20
LLAMA_MIN_P=0.0
LLAMA_PRESENCE_PENALTY=0.0
LLAMA_REPEAT_PENALTY=1.0

LLAMA_REASONING="auto"
LLAMA_CHAT_TEMPLATE_KWARGS=""

LLAMA_HOST="127.0.0.1"
LLAMA_PORT=1234
LLAMA_API_KEY_FILE=""
LLAMA_TIMEOUT=0
LLAMA_JINJA=1
LLAMA_METRICS=1

LLAMA_STARTUP_TIMEOUT=300
LLAMA_STOP_TIMEOUT=30
LLAMA_LOG_MAX_BYTES=52428800
LLAMA_LOG_BACKUPS=5
LLAMA_SYNC_CLIENTS=1

LLAMA_EXTRA_ARGS=()
